### ISSUE TITLE
switch to vite, ditch cra

### ISSUE THREAD

**Issue by gjoseph** [gjoseph/Tichu#574]
mostly encouraged by https://github.com/dilanx/craco/issues/426

see
https://github.com/vitejs/vite/discussions/5589
https://www.darraghoriordan.com/2021/05/16/migrating-from-create-react-app-to-vite/
and others...

**Comment by vish30** [comment]
Cannot use Vite as Rollup doesn't support module federation yet. Webpack is the goto option right now. IMO, it is very early to ditch CRA (Webpack).

**Comment by gjoseph** [comment]
done with #805
